version: '2'
services:
  ember:
      container_name: ember
      build:
        context: .
        dockerfile: docker_files/Dockerfile-dev
      ports:
        - "4200:4200"
        - "35729:35729"
      volumes:
        - ./ember-app/bower.json:/var/www/html/ember-app/bower.json
        - ./ember-app/package.json:/var/www/html/ember-app/package.json
        - ./ember-app/ember-cli-build.js:/var/www/html/ember-app/ember-cli-build.js
        - ./ember-app/.ember-cli:/var/www/html/ember-app/.ember-cli
        - ./ember-app/testem.js:/var/www/html/ember-app/testem.js
        - ./ember-app/app:/var/www/html/ember-app/app
        - ./ember-app/config:/var/www/html/ember-app/config
        - ./ember-app/public:/var/www/html/ember-app/public
        - ./ember-app/vendor:/var/www/html/ember-app/vendor
  php-apache:
    container_name: php-apache
    image: toozick/smu-arcade-machine-management-console-php-apache:v1
    links:
      - mysql
    ports:
      - "8080:80"
      - "9000:9000"
    volumes:
      - .:/var/www/html/
  mysql:
    container_name: mysql
    image: mysql:5.5
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: 8043v36m807c3084m6m03v
      MYSQL_PASSWORD: 8043v36m807c3084m6m03v
      MYSQL_DATABASE: SMUAdminConsole
