FROM toozick/smu-arcade-machine-management-console:v1

# Install Bower & NPM components
ADD ember-app /var/www/html/ember-app/
WORKDIR /var/www/html/ember-app
RUN bower install --allow-root --config.interactive=false
RUN npm install

# Ember addons
#sudo ember install ember-simple-auth
