FROM toozick/smu-arcade-machine-management-console:v1

WORKDIR /tmp

# Install Bower components
ADD ember-app/bower.json /tmp/bower.json
RUN bower install --allow-root --config.interactive=false
RUN mkdir -p /var/www/html/ember-app/bower_components && cp -a /tmp/bower_components /var/www/html/ember-app

# Install NodeJS components
ADD ember-app/package.json /tmp/package.json
RUN npm --cache-min 999999 install
RUN mkdir -p /var/www/html/ember-app/node_modules && cp -a /tmp/node_modules /var/www/html/ember-app

# Move all app code
#ADD . /var/www/html
WORKDIR /var/www/html

# Ember addonss
#sudo ember install ember-simple-auth
